# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.3"

pre_release = false

preface = """\
The fourth patch release for containerd 1.6 includes two fixes for CNI and SELinux.

### Notable Updates

* **Update go-cni to fix teardown regression** ([#6877](https://github.com/containerd/containerd/pull/6877))
* **Fix broken SELinux relabeling for Kubernetes volume mounts** ([#6878](https://github.com/containerd/containerd/pull/6878))

See the changelog for complete list of changes"""
